UPDATE public."Product" SET price = 5999, "salePrice" = 4499 WHERE name = 'Checkerboard Knit Mini Dress';
UPDATE public."Product" SET price = 5465, "salePrice" = 4099 WHERE name = 'Floral Mini Dress - Blue White';
UPDATE public."Product" SET price = 3332, "salePrice" = 2499 WHERE name = 'Collared Wrap Top - White';
UPDATE public."Product" SET price = 1867, "salePrice" = 1400 WHERE name = 'French Terry Cardigan - Verbena';
UPDATE public."Product" SET price = 2265, "salePrice" = 1699 WHERE name = 'Racerback Crop Tank - Red';
UPDATE public."Product" SET price = 1733, "salePrice" = 1300 WHERE name = 'Bubble Hem Party Top - Black Pink';
UPDATE public."Product" SET price = 2532, "salePrice" = 1899 WHERE name = 'Puff Sleeve Peplum Blouse - White';
UPDATE public."Product" SET price = 1600, "salePrice" = 1200 WHERE name = 'Slim Fit Baby Tee - White';
UPDATE public."Product" SET price = 4665, "salePrice" = 3499 WHERE name = 'Wide Cut Jeans - Grey';
UPDATE public."Product" SET price = 2265, "salePrice" = 1699 WHERE name = 'Women''s Blue Denim Shirt';
UPDATE public."Product" SET price = 7332, "salePrice" = 5499 WHERE name = 'Black Flared-Sleeve Maxi Dress';
UPDATE public."Product" SET price = 7332, "salePrice" = 5499 WHERE name = 'Butterfly Print Mesh Midi Dress';
UPDATE public."Product" SET price = 7332, "salePrice" = 5499 WHERE name = 'Cherry Print Slip Mini Dress';
UPDATE public."Product" SET price = 7332, "salePrice" = 5499 WHERE name = 'Strapless Jacquard Maxi Dress';
UPDATE public."Product" SET price = 5999, "salePrice" = 4499 WHERE name = 'Victoria Dress - Green/White';
UPDATE public."Product" SET price = 7332, "salePrice" = 5499 WHERE name = 'Red Floral Mesh Midi Dress';
UPDATE public."Product" SET price = 6532, "salePrice" = 4899 WHERE name = 'Embroidered Silk Saree - Wine';
UPDATE public."Product" SET price = 6132, "salePrice" = 4599 WHERE name = 'Organza Floral Saree - Ivory';
UPDATE public."Product" SET price = 7065, "salePrice" = 5299 WHERE name = 'Chanderi Silk Saree - Rose';
UPDATE public."Product" SET price = 5599, "salePrice" = 4199 WHERE name = 'Embroidered Anarkali - Maroon';
UPDATE public."Product" SET price = 5465, "salePrice" = 4099 WHERE name = 'Sharara Set - Dusty Pink';
UPDATE public."Product" SET price = 6665, "salePrice" = 4999 WHERE name = 'Rose Gold Lehenga Choli';
UPDATE public."Product" SET price = 4532, "salePrice" = 3399 WHERE name = 'Satin Slip Midi Dress - Champagne';
UPDATE public."Product" SET price = 4932, "salePrice" = 3699 WHERE name = 'Pleated Chiffon Maxi Dress - Sage';
UPDATE public."Product" SET price = 6532, "salePrice" = 4899 WHERE name = 'Tailored Blazer - Ivory';
UPDATE public."Product" SET price = 3732, "salePrice" = 2799 WHERE name = 'High-Rise Flare Jeans - Indigo';
UPDATE public."Product" SET price = 2799, "salePrice" = 2099 WHERE name = 'Satin Cowl-Neck Blouse - Champagne';
UPDATE public."Product" SET price = 2799, "salePrice" = 2099 WHERE name = 'Pleated Midi Skirt - Black';
UPDATE public."Product" SET price = 7999, "salePrice" = 5999 WHERE name = 'Mist Blue Printed Organza Saree Set';
UPDATE public."Product" SET price = 7999, "salePrice" = 5999 WHERE name = 'Black Chiffon Saree - Mirror Border';
UPDATE public."Product" SET price = 4265, "salePrice" = 3199 WHERE name = 'Grey Fit-and-Flare Midi Dress';
UPDATE public."Product" SET price = 6665, "salePrice" = 4999 WHERE name = 'Off White Hand Block Printed A-Line Kurta Set';
UPDATE public."Product" SET price = 6665, "salePrice" = 4999 WHERE name = 'Navy Satin Kurta Set with Floral Embroidery';
UPDATE public."Product" SET price = 1467, "salePrice" = 1100 WHERE name = 'Orange Floral Straight Suit Set';
UPDATE public."Product" SET price = 2932, "salePrice" = 2199 WHERE name = 'Blue Embroidered Cotton Straight Suit Set';
UPDATE public."Product" SET price = 2665, "salePrice" = 1999 WHERE name = 'Rust Cotton Anarkali Suit Set';
UPDATE public."Product" SET price = 2665, "salePrice" = 1999 WHERE name = 'Pink Printed Cotton Anarkali Suit Set';
UPDATE public."Product" SET price = 3999, "salePrice" = 2999 WHERE name = 'A-Line Midi Dress - Navy';
UPDATE public."Product" SET price = 4399, "salePrice" = 3299 WHERE name = 'Wrap Midi Dress - Rust';
UPDATE public."Product" SET price = 3732, "salePrice" = 2799 WHERE name = 'Linen Shirt Dress - Olive';
UPDATE public."Product" SET price = 4932, "salePrice" = 3699 WHERE name = 'Smocked Maxi Dress - Terracotta';
UPDATE public."Product" SET price = 4265, "salePrice" = 3199 WHERE name = 'Belted Shirt Dress - Khaki';
UPDATE public."Product" SET price = 3599, "salePrice" = 2699 WHERE name = 'Floral Tiered Dress - Coral';
UPDATE public."Product" SET price = 3332, "salePrice" = 2499 WHERE name = 'Ribbed Bodycon Midi - Black';
UPDATE public."Product" SET price = 3865, "salePrice" = 2899 WHERE name = 'Puff Sleeve Mini Dress - Lavender';
UPDATE public."Product" SET price = 2000, "salePrice" = 1500 WHERE name = 'Linen Crop Top - Sand';
UPDATE public."Product" SET price = 1733, "salePrice" = 1300 WHERE name = 'Oversized Cotton Tee - Stripe';
UPDATE public."Product" SET price = 2532, "salePrice" = 1899 WHERE name = 'Ruched Bardot Top - White';
UPDATE public."Product" SET price = 1600, "salePrice" = 1200 WHERE name = 'Knit Tank Top - Sage';
UPDATE public."Product" SET price = 2799, "salePrice" = 2099 WHERE name = 'Puff Sleeve Blouse - Cream';
UPDATE public."Product" SET price = 3065, "salePrice" = 2299 WHERE name = 'Satin Wrap Blouse - Emerald';
UPDATE public."Product" SET price = 2665, "salePrice" = 1999 WHERE name = 'Peplum Cotton Blouse - Dusty Blue';
UPDATE public."Product" SET price = 2399, "salePrice" = 1799 WHERE name = 'Tie-Front Blouse - Peach';
UPDATE public."Product" SET price = 5999, "salePrice" = 4499 WHERE name = 'Banarasi Silk Saree - Gold';
UPDATE public."Product" SET price = 5332, "salePrice" = 3999 WHERE name = 'Georgette Saree - Teal';
UPDATE public."Product" SET price = 4799, "salePrice" = 3599 WHERE name = 'Cotton Handloom Saree - Mustard';
UPDATE public."Product" SET price = 5199, "salePrice" = 3899 WHERE name = 'Pastel Ombre Saree - Blush';
UPDATE public."Product" SET price = 5732, "salePrice" = 4299 WHERE name = 'Zari Border Saree - Royal Blue';
UPDATE public."Product" SET price = 4399, "salePrice" = 3299 WHERE name = 'Printed Anarkali Kurta - Indigo';
UPDATE public."Product" SET price = 3065, "salePrice" = 2299 WHERE name = 'Cotton Straight Kurta - Mint';
UPDATE public."Product" SET price = 4932, "salePrice" = 3699 WHERE name = 'Kurta Set with Palazzo - Yellow';
UPDATE public."Product" SET price = 5332, "salePrice" = 3999 WHERE name = 'Sharara Set - Emerald';
UPDATE public."Product" SET price = 4799, "salePrice" = 3599 WHERE name = 'Anarkali Suit Set - Wine';
UPDATE public."Product" SET price = 4265, "salePrice" = 3199 WHERE name = 'Straight Suit with Dupatta - Beige';
UPDATE public."Product" SET price = 5999, "salePrice" = 4499 WHERE name = 'Printed Lehenga Set - Peach';
UPDATE public."Product" SET price = 5199, "salePrice" = 3899 WHERE name = 'Chikankari Kurta Set - White';
UPDATE public."Product" SET price = 3465, "salePrice" = 2599 WHERE name = 'Mom Fit Jeans - Light Blue';
UPDATE public."Product" SET price = 3332, "salePrice" = 2499 WHERE name = 'Skinny High-Rise Jeans - Black';
UPDATE public."Product" SET price = 3732, "salePrice" = 2799 WHERE name = 'Cropped Wide Jeans - Washed Blue';
UPDATE public."Product" SET price = 2532, "salePrice" = 1899 WHERE name = 'A-Line Midi Skirt - Denim';
UPDATE public."Product" SET price = 2665, "salePrice" = 1999 WHERE name = 'Pleated Maxi Skirt - Olive';
UPDATE public."Product" SET price = 2399, "salePrice" = 1799 WHERE name = 'Wrap Midi Skirt - Burgundy';
UPDATE public."Product" SET price = 2265, "salePrice" = 1699 WHERE name = 'Cotton Shrug - Ivory';
UPDATE public."Product" SET price = 2799, "salePrice" = 2099 WHERE name = 'Knit Cardigan - Camel';
UPDATE public."Product" SET price = 3999, "salePrice" = 2999 WHERE name = 'Denim Jacket - Light Wash';
UPDATE public."Product" SET price = 4932, "salePrice" = 3699 WHERE name = 'Trench Coat - Beige';
UPDATE public."Product" SET price = 3465, "salePrice" = 2599 WHERE name = 'Quilted Puffer Vest - Stone';
UPDATE public."Product" SET price = 2532, "salePrice" = 1899 WHERE name = 'Lace Trim Blouse - Ivory';
UPDATE public."Product" SET price = 2665, "salePrice" = 1999 WHERE name = 'Striped Office Blouse - Navy';
UPDATE public."Product" SET price = 2399, "salePrice" = 1799 WHERE name = 'Ruffled Chiffon Blouse - Blush';
UPDATE public."Product" SET price = 2265, "salePrice" = 1699 WHERE name = 'Floral Cotton Blouse - Green';
UPDATE public."Product" SET price = 2799, "salePrice" = 2099 WHERE name = 'High-Neck Satin Blouse - Black';
UPDATE public."Product" SET price = 2399, "salePrice" = 1799 WHERE name = 'Bell Sleeve Blouse - Mustard';
UPDATE public."Product" SET price = 3332, "salePrice" = 2499 WHERE name = 'Boyfriend Jeans - Mid Blue';
UPDATE public."Product" SET price = 3465, "salePrice" = 2599 WHERE name = 'Straight Leg Jeans - Dark Wash';
UPDATE public."Product" SET price = 3599, "salePrice" = 2699 WHERE name = 'High-Rise Bootcut Jeans - Indigo';
UPDATE public."Product" SET price = 3199, "salePrice" = 2399 WHERE name = 'Distressed Slim Jeans - Light Wash';
UPDATE public."Product" SET price = 3332, "salePrice" = 2499 WHERE name = 'Cargo Jeans - Olive';
UPDATE public."Product" SET price = 3599, "salePrice" = 2699 WHERE name = 'Paperbag Waist Jeans - Cream';
