UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Checkerboard Knit Mini Dress';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Floral Mini Dress - Blue White';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Casual everyday' WHERE name = 'Collared Wrap Top - White';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Everyday wear' WHERE name = 'French Terry Cardigan - Verbena';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Casual everyday' WHERE name = 'Racerback Crop Tank - Red';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Party & evening' WHERE name = 'Bubble Hem Party Top - Black Pink';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'Puff Sleeve Peplum Blouse - White';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Casual everyday' WHERE name = 'Slim Fit Baby Tee - White';
UPDATE public."Product" SET "careInfo" = 'Machine wash cold, inside out. Do not bleach. Tumble dry low.', occasion = 'Casual everyday' WHERE name = 'Wide Cut Jeans - Grey';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Everyday wear' WHERE name = 'Women''s Blue Denim Shirt';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Black Flared-Sleeve Maxi Dress';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Butterfly Print Mesh Midi Dress';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Cherry Print Slip Mini Dress';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Party & evening' WHERE name = 'Strapless Jacquard Maxi Dress';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Victoria Dress - Green/White';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Red Floral Mesh Midi Dress';
UPDATE public."Product" SET "careInfo" = 'Dry clean recommended. Store folded in a muslin bag away from direct sunlight.', occasion = 'Festive & wedding' WHERE name = 'Embroidered Silk Saree - Wine';
UPDATE public."Product" SET "careInfo" = 'Dry clean recommended. Store folded in a muslin bag away from direct sunlight.', occasion = 'Festive & wedding' WHERE name = 'Organza Floral Saree - Ivory';
UPDATE public."Product" SET "careInfo" = 'Dry clean recommended. Store folded in a muslin bag away from direct sunlight.', occasion = 'Festive & wedding' WHERE name = 'Chanderi Silk Saree - Rose';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Embroidered Anarkali - Maroon';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Sharara Set - Dusty Pink';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Rose Gold Lehenga Choli';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Satin Slip Midi Dress - Champagne';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Pleated Chiffon Maxi Dress - Sage';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Work & smart casual' WHERE name = 'Tailored Blazer - Ivory';
UPDATE public."Product" SET "careInfo" = 'Machine wash cold, inside out. Do not bleach. Tumble dry low.', occasion = 'Casual everyday' WHERE name = 'High-Rise Flare Jeans - Indigo';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'Satin Cowl-Neck Blouse - Champagne';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Everyday wear' WHERE name = 'Pleated Midi Skirt - Black';
UPDATE public."Product" SET "careInfo" = 'Dry clean recommended. Store folded in a muslin bag away from direct sunlight.', occasion = 'Festive & wedding' WHERE name = 'Mist Blue Printed Organza Saree Set';
UPDATE public."Product" SET "careInfo" = 'Dry clean recommended. Store folded in a muslin bag away from direct sunlight.', occasion = 'Festive & wedding' WHERE name = 'Black Chiffon Saree - Mirror Border';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Grey Fit-and-Flare Midi Dress';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Off White Hand Block Printed A-Line Kurta Set';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Navy Satin Kurta Set with Floral Embroidery';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Orange Floral Straight Suit Set';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Blue Embroidered Cotton Straight Suit Set';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Rust Cotton Anarkali Suit Set';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Pink Printed Cotton Anarkali Suit Set';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'A-Line Midi Dress - Navy';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Wrap Midi Dress - Rust';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Linen Shirt Dress - Olive';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Smocked Maxi Dress - Terracotta';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Belted Shirt Dress - Khaki';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Floral Tiered Dress - Coral';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Ribbed Bodycon Midi - Black';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Day to evening' WHERE name = 'Puff Sleeve Mini Dress - Lavender';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Casual everyday' WHERE name = 'Linen Crop Top - Sand';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Casual everyday' WHERE name = 'Oversized Cotton Tee - Stripe';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Party & evening' WHERE name = 'Ruched Bardot Top - White';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Casual everyday' WHERE name = 'Knit Tank Top - Sage';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'Puff Sleeve Blouse - Cream';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'Satin Wrap Blouse - Emerald';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'Peplum Cotton Blouse - Dusty Blue';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'Tie-Front Blouse - Peach';
UPDATE public."Product" SET "careInfo" = 'Dry clean recommended. Store folded in a muslin bag away from direct sunlight.', occasion = 'Festive & wedding' WHERE name = 'Banarasi Silk Saree - Gold';
UPDATE public."Product" SET "careInfo" = 'Dry clean recommended. Store folded in a muslin bag away from direct sunlight.', occasion = 'Festive & wedding' WHERE name = 'Georgette Saree - Teal';
UPDATE public."Product" SET "careInfo" = 'Dry clean recommended. Store folded in a muslin bag away from direct sunlight.', occasion = 'Festive & wedding' WHERE name = 'Cotton Handloom Saree - Mustard';
UPDATE public."Product" SET "careInfo" = 'Dry clean recommended. Store folded in a muslin bag away from direct sunlight.', occasion = 'Festive & wedding' WHERE name = 'Pastel Ombre Saree - Blush';
UPDATE public."Product" SET "careInfo" = 'Dry clean recommended. Store folded in a muslin bag away from direct sunlight.', occasion = 'Festive & wedding' WHERE name = 'Zari Border Saree - Royal Blue';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Printed Anarkali Kurta - Indigo';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Cotton Straight Kurta - Mint';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Kurta Set with Palazzo - Yellow';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Sharara Set - Emerald';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Anarkali Suit Set - Wine';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Straight Suit with Dupatta - Beige';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Printed Lehenga Set - Peach';
UPDATE public."Product" SET "careInfo" = 'Gentle hand wash or dry clean. Iron on reverse at low heat.', occasion = 'Festive & celebrations' WHERE name = 'Chikankari Kurta Set - White';
UPDATE public."Product" SET "careInfo" = 'Machine wash cold, inside out. Do not bleach. Tumble dry low.', occasion = 'Casual everyday' WHERE name = 'Mom Fit Jeans - Light Blue';
UPDATE public."Product" SET "careInfo" = 'Machine wash cold, inside out. Do not bleach. Tumble dry low.', occasion = 'Casual everyday' WHERE name = 'Skinny High-Rise Jeans - Black';
UPDATE public."Product" SET "careInfo" = 'Machine wash cold, inside out. Do not bleach. Tumble dry low.', occasion = 'Casual everyday' WHERE name = 'Cropped Wide Jeans - Washed Blue';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Everyday wear' WHERE name = 'A-Line Midi Skirt - Denim';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Everyday wear' WHERE name = 'Pleated Maxi Skirt - Olive';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Everyday wear' WHERE name = 'Wrap Midi Skirt - Burgundy';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Everyday wear' WHERE name = 'Cotton Shrug - Ivory';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Everyday wear' WHERE name = 'Knit Cardigan - Camel';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Work & smart casual' WHERE name = 'Denim Jacket - Light Wash';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Work & smart casual' WHERE name = 'Trench Coat - Beige';
UPDATE public."Product" SET "careInfo" = 'Follow care label. Wash separately for first few wears.', occasion = 'Work & smart casual' WHERE name = 'Quilted Puffer Vest - Stone';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'Lace Trim Blouse - Ivory';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'Striped Office Blouse - Navy';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'Ruffled Chiffon Blouse - Blush';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'Floral Cotton Blouse - Green';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'High-Neck Satin Blouse - Black';
UPDATE public."Product" SET "careInfo" = 'Hand wash cold or gentle machine cycle. Lay flat to dry. Cool iron if needed.', occasion = 'Everyday wear' WHERE name = 'Bell Sleeve Blouse - Mustard';
UPDATE public."Product" SET "careInfo" = 'Machine wash cold, inside out. Do not bleach. Tumble dry low.', occasion = 'Casual everyday' WHERE name = 'Boyfriend Jeans - Mid Blue';
UPDATE public."Product" SET "careInfo" = 'Machine wash cold, inside out. Do not bleach. Tumble dry low.', occasion = 'Casual everyday' WHERE name = 'Straight Leg Jeans - Dark Wash';
UPDATE public."Product" SET "careInfo" = 'Machine wash cold, inside out. Do not bleach. Tumble dry low.', occasion = 'Casual everyday' WHERE name = 'High-Rise Bootcut Jeans - Indigo';
UPDATE public."Product" SET "careInfo" = 'Machine wash cold, inside out. Do not bleach. Tumble dry low.', occasion = 'Casual everyday' WHERE name = 'Distressed Slim Jeans - Light Wash';
UPDATE public."Product" SET "careInfo" = 'Machine wash cold, inside out. Do not bleach. Tumble dry low.', occasion = 'Casual everyday' WHERE name = 'Cargo Jeans - Olive';
UPDATE public."Product" SET "careInfo" = 'Machine wash cold, inside out. Do not bleach. Tumble dry low.', occasion = 'Casual everyday' WHERE name = 'Paperbag Waist Jeans - Cream';
